language: python
sudo: required
virtualenv:
  system_site_packages: true
env:
  matrix:
    #- PYTHON_VERSION="2.7"  ANUGA_PARALLEL="openmpi"  DISTRIB="conda"
    - PYTHON_VERSION="2.7"  ANUGA_PARALLEL="openmpi"  DISTRIB="ubuntu"
    #- PYTHON_VERSION="2.7"  ANUGA_PARALLEL="mpich2"  DISTRIB="conda"
    - PYTHON_VERSION="2.7"  ANUGA_PARALLEL="mpich2"  DISTRIB="ubuntu" COVERAGE="--coverage"
    - PYTHON_VERSION="2.7"  ANUGA_PARALLEL="false"   DISTRIB="ubuntu"
    #- PYTHON_VERSION="2.6"  ANUGA_PARALLEL="false"   DISTRIB="conda"

install: 
    - if [[ "$DISTRIB" == "conda" ]]; then source tools/install_conda.sh; fi
    - if [[ "$DISTRIB" == "ubuntu" ]]; then source tools/install_ubuntu.sh; fi
    - if [[ "$COVERAGE" == "--coverage" ]]; then pip install coverage coveralls; fi
    - python setup.py install

script: 
    - python runtests.py $COVERAGE
    - if [[ "$COVERAGE" == "--coverage" ]]; then cp build/test/.coverage .; fi

after_success:
    - if [[ "$COVERAGE" == "--coverage" ]]; then coveralls || echo "failed"; fi






