skip_tags: true
clone_depth: 1

os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86"
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"

build_script:
# If there's a newer build queued for the same PR, cancel this one
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - ps: Start-FileDownload "https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisetup.exe" C:\msmpisetup.exe; echo "Finished downloading msmpi"
  - ps: Start-FileDownload "https://download.microsoft.com/download/A/E/0/AE002626-9D9D-448D-8197-1EA510E297CE/msmpisdk.msi" C:\msmpisdk.msi; echo "Finished downloading msmpisdk"
  - cmd: msiexec.exe /i "C:\msmpisdk.msi" /qn
  - cmd: C:\msmpisetup.exe -unattend
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - cmd: C:\Py\Scripts\activate.bat
  - CMD: SET
  - set PATH=%PATH%;"C:\Program Files\Microsoft MPI\bin"
  - conda config --set always_yes yes
  - conda update conda
  - conda install python=3.8 gdal nose numpy cython scipy netcdf4 matplotlib dill future
  - conda install -c m2w64 libpython m2w64-toolchain
  - pip install mpi4py
  - python setup.py install

test_script:
  - python runtests.py
